name: CI deploy to SockeServer
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Build project
        run: npm run build

      - name: Movendo dist para a pasta de projetos
        run: mv actions-runner/_work/SocketServer/SocketServer/dist ~/projects/SocketServer

      - name: Start/Reload PM2
        run: pm2 restart 'Socket Server' --update-env