name: CI deploy to SockeServer
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Movendo dist para a pasta de projetos
        run: |
          rm -r ~/projects/SocketServer
          mv /actions-runner/_work/SocketServer/SocketServer ~/projects/

      - name: Install
        run: |
          cd ~/projects/SocketServer
          npm install

      - name: Start/Reload PM2
        run: pm2 restart 'Socket Server' --update-env