name: CI deploy to SockeServer
on:
  push:
    branches:
      - master
    paths: /root/projects

  pull_request:
    branches:
      - master
    paths: /root/projects

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: npm install

      # - name: Apagando o projeto antigo e movendo o novo para a pasta ~/projects
      #   run: |
      #     rm -r /root/projects/SocketServer
      #     mv /actions-runner/_work/SocketServer/SocketServer /root/projects

      - name: Start/Reload PM2
        run: pm2 restart 'Socket Server' --update-env